function synthetize (schema) {
  const { Bundle } = require('./bundle')

  let group = module.exports
  for (let part of schema.apiVersion.split(/[./]/)) group = group[part] = group[part] || {}

  group[schema.kind] = class extends Bundle {
    constructor () {
      super()
      Object.assign(this, arguments[0])
    }

    getAllResources () {
      const obj = {
        apiVersion: schema.apiVersion,
        kind: schema.kind
      }
      const that = Object.assign({}, this)
      delete that.solsa
      if (schema.metadata) {
        obj.metadata = { name: this.name, labels: this.labels, annotations: this.annotations }
        delete that.name
        delete that.labels
        delete that.annotations
      }
      if (schema.spec) {
        const spec = Object.assign({}, that.spec)
        delete that.spec
        obj.spec = Object.assign(spec, that)
      } else {
        Object.assign(obj, that)
      }
      return [{ obj, name: this.name + '-' + schema.apiVersion.replace(/[./]/g, '-') + '-' + schema.kind + '.yaml' }]
    }
  }
}

synthetize({ 'apiVersion': 'admissionregistration.k8s.io/v1beta1', 'kind': 'MutatingWebhookConfiguration', 'metadata': 1 })
synthetize({ 'apiVersion': 'admissionregistration.k8s.io/v1beta1', 'kind': 'MutatingWebhookConfigurationList', 'metadata': 1 })
synthetize({ 'apiVersion': 'admissionregistration.k8s.io/v1beta1', 'kind': 'ValidatingWebhookConfiguration', 'metadata': 1 })
synthetize({ 'apiVersion': 'admissionregistration.k8s.io/v1beta1', 'kind': 'ValidatingWebhookConfigurationList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'ControllerRevision', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'ControllerRevisionList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'DaemonSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'DaemonSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'Deployment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'DeploymentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'ReplicaSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'ReplicaSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'StatefulSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1', 'kind': 'StatefulSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'ControllerRevision', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'ControllerRevisionList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'Deployment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'DeploymentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'DeploymentRollback' })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'Scale', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'StatefulSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta1', 'kind': 'StatefulSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'ControllerRevision', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'ControllerRevisionList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'DaemonSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'DaemonSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'Deployment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'DeploymentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'ReplicaSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'ReplicaSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'Scale', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'StatefulSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apps/v1beta2', 'kind': 'StatefulSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'auditregistration.k8s.io/v1alpha1', 'kind': 'AuditSink', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'auditregistration.k8s.io/v1alpha1', 'kind': 'AuditSinkList', 'metadata': 1 })
synthetize({ 'apiVersion': 'authentication.k8s.io/v1', 'kind': 'TokenReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authentication.k8s.io/v1beta1', 'kind': 'TokenReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1', 'kind': 'LocalSubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1', 'kind': 'SelfSubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1', 'kind': 'SelfSubjectRulesReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1', 'kind': 'SubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1beta1', 'kind': 'LocalSubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1beta1', 'kind': 'SelfSubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1beta1', 'kind': 'SelfSubjectRulesReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'authorization.k8s.io/v1beta1', 'kind': 'SubjectAccessReview', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'autoscaling/v1', 'kind': 'HorizontalPodAutoscaler', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'autoscaling/v1', 'kind': 'HorizontalPodAutoscalerList', 'metadata': 1 })
synthetize({ 'apiVersion': 'autoscaling/v1', 'kind': 'Scale', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'autoscaling/v2beta1', 'kind': 'HorizontalPodAutoscaler', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'autoscaling/v2beta1', 'kind': 'HorizontalPodAutoscalerList', 'metadata': 1 })
synthetize({ 'apiVersion': 'autoscaling/v2beta2', 'kind': 'HorizontalPodAutoscaler', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'autoscaling/v2beta2', 'kind': 'HorizontalPodAutoscalerList', 'metadata': 1 })
synthetize({ 'apiVersion': 'batch/v1', 'kind': 'Job', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'batch/v1', 'kind': 'JobList', 'metadata': 1 })
synthetize({ 'apiVersion': 'batch/v1beta1', 'kind': 'CronJob', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'batch/v1beta1', 'kind': 'CronJobList', 'metadata': 1 })
synthetize({ 'apiVersion': 'batch/v2alpha1', 'kind': 'CronJob', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'batch/v2alpha1', 'kind': 'CronJobList', 'metadata': 1 })
synthetize({ 'apiVersion': 'certificates.k8s.io/v1beta1', 'kind': 'CertificateSigningRequest', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'certificates.k8s.io/v1beta1', 'kind': 'CertificateSigningRequestList', 'metadata': 1 })
synthetize({ 'apiVersion': 'coordination.k8s.io/v1', 'kind': 'Lease', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'coordination.k8s.io/v1', 'kind': 'LeaseList', 'metadata': 1 })
synthetize({ 'apiVersion': 'coordination.k8s.io/v1beta1', 'kind': 'Lease', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'coordination.k8s.io/v1beta1', 'kind': 'LeaseList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Binding', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ComponentStatus', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ComponentStatusList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ConfigMap', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ConfigMapList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Endpoints', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'EndpointsList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Event', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'EventList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'LimitRange', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'LimitRangeList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'NamespaceList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Node', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'NodeList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PersistentVolume', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PersistentVolumeClaim', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PersistentVolumeClaimList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PersistentVolumeList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Pod', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PodList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PodTemplate', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'PodTemplateList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ReplicationController', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ReplicationControllerList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ResourceQuota', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ResourceQuotaList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Secret', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'SecretList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'Service', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ServiceAccount', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ServiceAccountList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'ServiceList', 'metadata': 1 })
synthetize({ 'apiVersion': 'events.k8s.io/v1beta1', 'kind': 'Event', 'metadata': 1 })
synthetize({ 'apiVersion': 'events.k8s.io/v1beta1', 'kind': 'EventList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'DaemonSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'DaemonSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'Deployment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'DeploymentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'DeploymentRollback' })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'Ingress', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'IngressList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'NetworkPolicy', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'NetworkPolicyList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'PodSecurityPolicy', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'PodSecurityPolicyList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'ReplicaSet', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'ReplicaSetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'extensions/v1beta1', 'kind': 'Scale', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'networking.k8s.io/v1', 'kind': 'NetworkPolicy', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'networking.k8s.io/v1', 'kind': 'NetworkPolicyList', 'metadata': 1 })
synthetize({ 'apiVersion': 'networking.k8s.io/v1beta1', 'kind': 'Ingress', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'networking.k8s.io/v1beta1', 'kind': 'IngressList', 'metadata': 1 })
synthetize({ 'apiVersion': 'node.k8s.io/v1alpha1', 'kind': 'RuntimeClass', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'node.k8s.io/v1alpha1', 'kind': 'RuntimeClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'node.k8s.io/v1beta1', 'kind': 'RuntimeClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'node.k8s.io/v1beta1', 'kind': 'RuntimeClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'policy/v1beta1', 'kind': 'Eviction', 'metadata': 1 })
synthetize({ 'apiVersion': 'policy/v1beta1', 'kind': 'PodDisruptionBudget', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'policy/v1beta1', 'kind': 'PodDisruptionBudgetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'policy/v1beta1', 'kind': 'PodSecurityPolicy', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'policy/v1beta1', 'kind': 'PodSecurityPolicyList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRole', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'ClusterRoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'Role', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'RoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'RoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'RoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'ClusterRole', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'ClusterRoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'ClusterRoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'ClusterRoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'Role', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'RoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'RoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1alpha1', 'kind': 'RoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'ClusterRole', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'ClusterRoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'ClusterRoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'ClusterRoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'Role', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'RoleBinding', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'RoleBindingList', 'metadata': 1 })
synthetize({ 'apiVersion': 'rbac.authorization.k8s.io/v1beta1', 'kind': 'RoleList', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1', 'kind': 'PriorityClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1', 'kind': 'PriorityClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1alpha1', 'kind': 'PriorityClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1alpha1', 'kind': 'PriorityClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1beta1', 'kind': 'PriorityClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'scheduling.k8s.io/v1beta1', 'kind': 'PriorityClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'settings.k8s.io/v1alpha1', 'kind': 'PodPreset', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'settings.k8s.io/v1alpha1', 'kind': 'PodPresetList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1', 'kind': 'VolumeAttachment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1', 'kind': 'VolumeAttachmentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1alpha1', 'kind': 'VolumeAttachment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1alpha1', 'kind': 'VolumeAttachmentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'CSIDriver', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'CSIDriverList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'CSINode', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'CSINodeList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'StorageClass', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'StorageClassList', 'metadata': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'VolumeAttachment', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'storage.k8s.io/v1beta1', 'kind': 'VolumeAttachmentList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apiextensions.k8s.io/v1beta1', 'kind': 'CustomResourceDefinition', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apiextensions.k8s.io/v1beta1', 'kind': 'CustomResourceDefinitionList', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'APIGroup' })
synthetize({ 'apiVersion': 'v1', 'kind': 'APIGroupList' })
synthetize({ 'apiVersion': 'v1', 'kind': 'APIResourceList' })
synthetize({ 'apiVersion': 'v1', 'kind': 'APIVersions' })
synthetize({ 'apiVersion': 'v1', 'kind': 'DeleteOptions' })
synthetize({ 'apiVersion': 'v1', 'kind': 'Status', 'metadata': 1 })
synthetize({ 'apiVersion': 'v1', 'kind': 'WatchEvent' })
synthetize({ 'apiVersion': 'apiregistration.k8s.io/v1', 'kind': 'APIService', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apiregistration.k8s.io/v1', 'kind': 'APIServiceList', 'metadata': 1 })
synthetize({ 'apiVersion': 'apiregistration.k8s.io/v1beta1', 'kind': 'APIService', 'metadata': 1, 'spec': 1 })
synthetize({ 'apiVersion': 'apiregistration.k8s.io/v1beta1', 'kind': 'APIServiceList', 'metadata': 1 })
